spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testb5f4?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update