server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_batis_example
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    port: 6379
    host: localhost
  cache:
    type: redis

logging:
  level:
    org:
      springframework:
        cache: DEBUG
        data:
          redis: DEBUG

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
  global-config:
    db-config:
      id-type: auto # ID 主键自增
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: viosmash.dataobject



