
server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: test-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/test/**

        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**
  main:
    webApplicationType: reactive