spring:
  application:
    name: test
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:60000/realms/test
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: alibout-rest-api
      principle-attribute: preferred_username

server:
  port: 8080

